version: '3.8'

services:
  https-monitor:
    build: .
    container_name: https-monitor
    ports:
      - "3000:3000"
    volumes:
      - ./urls.json:/app/urls.json # Persistência do "banco de dados"
    # env_file:
    #   - .env
    restart: unless-stopped
